org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=nofishinghook
mod.name=No Fishing Hook
mod.group=bluebird
mod.version=1.0
mod.authors=BluebirdDevs
mod.contributors=
mod.license=ARR
mod.description=Removes the annoying fishing rod bobber/hook in first person allowing you to see clearer
mod.sources_url=https://github.com/BluebirdDevs/NoFishingHook
mod.homepage_url=https://github.com/BluebirdDevs/NoFishingHook
mod.issues_url=https://github.com/BluebirdDevs/NoFishingHook/issues

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

# Publishing
publish.dryrun=false

publish.modrinth.id=QigeLZ9G
publish.curseforge.id=1558064

publish.modrinth=false
publish.curseforge=false

publish.release.fabric=stable
publish.release.neoforge=stable
publish.release.forge=stable
